### ISSUE TITLE
Allow mounting from fstab with `user` option

### ISSUE THREAD

**Issue by n-st** [N-Coder/studip-fuse#8]
It would be useful to be able to add a studip-fuse mount to `/etc/fstab` and mount it on demand (through the `noauto` and `user` mount options):

    studip-fuse#doe123    /home/johndoe/StudIP.fuse    fuse    noauto,user,ro,allow-other,uid=1000,gid=1000,pwfile=/home/johndoe/.config/studip-fuse/.studip-pw

**Problem:** Unfortunately, this is impossible at the moment: the `user` option "implies the options  noexec, nosuid, and nodev" (see `man 8 mount`), which causes `studip-fuse` to abort:

    studip-fuse: error: unrecognized arguments: --noexec

**Solution:** Since `studip-fuse` doesn't produce virtual files with executable, suid, or device attributes anyway, both the positive (`--exec`) and negative (`--noexec`) can be simply ignored without causing any problems.

**Comment by N-Coder** [comment]
Fixed by #9
